Added tests for Python 3.10
RegioHelden/django-scrubber pull request #43
Opened 2022-06-22 16:50 UTC by GitRon

Just saw that we are not up-to-date 🙂

2022-06-22 16:52 UTC, GitRon commented
@costela fyi

2022-06-22 20:25 UTC, costela requested changes
thanks! good catch!

just a small nitpick :sweat_smile:

2022-06-22 20:25 UTC, costela commented on .github/workflows/workflow.yaml
> +          - "3.10"
nitpicking: can we use the same format for the whole list?

2022-06-23 06:31 UTC, GitRon commented
@costela done

2022-06-23 06:42 UTC, costela approved these changes

2022-06-23 06:43 UTC, merged