Updated versions in GitHub workflow and updated supported versions
RegioHelden/django-scrubber pull request #48
Opened 2023-03-02 16:49 UTC by GitRon

Hi @lociii & @costela 

I just updated the docs for PyPI and the GitHub actions. Let's see if it runs through 🙃

2023-03-02 17:05 UTC, lociii commented
I'd be fine in removing Python 3.7 support completely as it's EOL in 3 months anyways.

2023-03-03 07:59 UTC, costela requested changes
Thanks as always for the work! :medal_sports: 

Just some minor notes :wink:

2023-03-03 07:59 UTC, costela commented on .github/workflows/workflow.yaml
> +    runs-on: ubuntu-23.04
I think it's generally safer (in the sense of "principle of least surprise") to use LTS versions?

2023-03-03 07:59 UTC, costela commented on .github/workflows/workflow.yaml
> +          python-version: 3.1
don't you mean this?
```suggestion
          python-version: "3.10"
```

2023-03-03 07:59 UTC, costela commented on .github/workflows/workflow.yaml
> +    runs-on: ubuntu-23.04
dito: LTS is probably better?

2023-03-03 07:59 UTC, costela commented on .github/workflows/workflow.yaml
> +          - "3.11"
as @lociii said, we can probably drop 3.7 here :wink:

2023-03-03 07:59 UTC, costela commented on .github/workflows/workflow.yaml
> +            django: 4.1
if we do drop 3.7, we can drop these too, right?

2023-03-03 07:59 UTC, costela commented on .github/workflows/workflow.yaml
> +    runs-on: ubuntu-23.04
LTS :wink:

2023-03-03 07:59 UTC, costela commented on setup.py
>          'Programming Language :: Python :: 3.7',
```suggestion
```

2023-03-03 08:19 UTC, GitRon commented
@lociii @costela Good remarks, updated the PR!

2023-03-03 08:22 UTC, GitRon commented
Any idea why the pipeline is not running through? 🤔

2023-03-03 08:31 UTC, GitRon commented
Found something, we'll see if it helps.

2023-03-03 08:55 UTC, lociii commented
LGTM now. Great work as always. Thanks for keeping the setup up to date.

2023-03-03 08:55 UTC, merged

2023-03-03 08:56 UTC, GitRon commented
Thx! No problem. I hope that we get this package to the next level - together 🙃